#!/usr/bin/env bash
set -euo pipefail

# Generates a Baseline Profile for react-native-notify-kit by running
# the macrobenchmark test on a connected device, then filters and copies
# the result into the library's src/main/baseline-prof.txt.
#
# Prerequisites:
#   - A physical device connected via adb (Pixel 9 Pro XL with Android 16+ recommended)
#   - OR a running emulator with API 33+ and aosp/aosp-atd system image
#   - The smoke app must be buildable (run yarn install first)
#
# Usage: bash scripts/generate-baseline-profile.sh

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SMOKE_ANDROID="$REPO_ROOT/apps/smoke/android"
LIBRARY_PROFILE="$REPO_ROOT/packages/react-native/android/src/main/baseline-prof.txt"

echo "→ Verifying adb device connection..."
DEVICE_COUNT=$(adb devices | grep -w "device" | grep -v "List" | wc -l | tr -d ' ')
if [[ "$DEVICE_COUNT" -eq 0 ]]; then
    echo "❌ No adb device connected. Connect a device and enable USB debugging."
    exit 1
elif [[ "$DEVICE_COUNT" -gt 1 ]]; then
    echo "❌ Multiple adb devices detected — baseline profile generation requires exactly one:"
    echo ""
    adb devices
    echo ""
    echo "This often happens when both USB and WiFi ADB are active for the same physical device."
    echo "Options:"
    echo "  1. Disconnect WiFi ADB:      adb disconnect <ip>:5555"
    echo "  2. Specify a target device:  ANDROID_SERIAL=<serial> bash scripts/generate-baseline-profile.sh"
    exit 1
fi

echo "→ Running :app:generateBaselineProfile (this can take several minutes)..."
cd "$SMOKE_ANDROID"
./gradlew :app:generateBaselineProfile

# The generated profile path varies by AGP version. Search common locations.
GENERATED=$(find "$SMOKE_ANDROID/app/src" -name "baseline-prof.txt" 2>/dev/null | head -1)
if [[ -z "$GENERATED" ]]; then
    GENERATED=$(find "$SMOKE_ANDROID/app/build/outputs" -name "baseline-prof.txt" 2>/dev/null | head -1)
fi
if [[ -z "$GENERATED" || ! -f "$GENERATED" ]]; then
    echo "❌ Could not locate generated baseline-prof.txt under $SMOKE_ANDROID/app/"
    echo "   Check the Gradle task output for errors."
    exit 1
fi
echo "→ Found generated profile at $GENERATED"

echo "→ Filtering profile to library-only rules..."
{
    echo "# Baseline Profile for react-native-notify-kit"
    echo "# Generated by apps/smoke/android/baselineprofile — do not edit by hand"
    echo "# Regenerate with: bash scripts/generate-baseline-profile.sh"
    echo ""
    # Keep only rules matching the library's Java packages
    grep -E "Lapp/notifee/core" "$GENERATED" || true
    grep -E "Lio/invertase/notifee" "$GENERATED" || true
} > "$LIBRARY_PROFILE"

RULE_COUNT=$(grep -cE "^(HSP|HS|HP|H|SP|S|P|L)" "$LIBRARY_PROFILE" || echo 0)
echo "✅ Baseline profile copied to $LIBRARY_PROFILE ($RULE_COUNT rules)"
echo ""
echo "Next steps:"
echo "  1. Review the generated profile for unexpected entries"
echo "  2. Commit $LIBRARY_PROFILE to git"
echo "  3. Publish a new version of react-native-notify-kit"
