name: Code Quality Checks

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linting:
    name: Lint
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 1
      - name: Enable Corepack
        run: corepack enable
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'yarn'
      - name: Configure JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Yarn Install
        uses: nick-fields/retry@v4
        with:
          timeout_minutes: 3
          retry_wait_seconds: 30
          max_attempts: 3
          command: yarn install --immutable
      - name: Lint javascript
        run: yarn validate:all:js
      - name: Lint Native - validate:all:check
        run: yarn format:all:check

  typescript:
    name: TypeScript Build Validation
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 1
      - name: Enable Corepack
        run: corepack enable
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'yarn'
      - name: Yarn Install
        uses: nick-fields/retry@v4
        with:
          timeout_minutes: 3
          retry_wait_seconds: 30
          max_attempts: 3
          command: yarn install --immutable
      - name: Lint
        run: yarn validate:all:ts

  typedoc:
    name: TypeDoc Generation
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 1
      - name: Enable Corepack
        run: corepack enable
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'yarn'
      - name: Yarn Install
        uses: nick-fields/retry@v4
        with:
          timeout_minutes: 3
          retry_wait_seconds: 30
          max_attempts: 3
          command: yarn install --immutable
      - name: Generate TypeDoc
        run: yarn gen:reference
